### ISSUE TITLE
Default / XML output format doesn't work with JDK 11

### ISSUE THREAD

**Issue by tdddblog** [NASA-PDS/registry-api-service#54]
## 🐛 Describe the bug
API server doesn't work (returns status 500) with default output format with JDK11

## 📜 To Reproduce
1. Go to http://localhost:8080/bundles
4. See 500 error

## 🕵️ Expected behavior
If XML output format is supported, it should work with JDK11.

## 📚 Version of Software Used
API: 0.3.0.

## 🩺 Stack Trace
```
2021-07-22 14:44:38.549 ERROR 17384 --- [nio-8080-exec-8] o.a.c.c.C.[.[.[/].[dispatcherServlet]    : Servlet.service() for servlet [dispatcherServlet] in context with path [] threw exception [Request processing failed; nested exception is org.springframework.http.converter.HttpMessageConversionException: Could not create JAXBContext for class [class gov.nasa.pds.model.Products]: Implementation of JAXB-API has not been found on module path or classpath.; nested exception is javax.xml.bind.JAXBException: Implementation of JAXB-API has not been found on module path or classpath.
 - with linked exception:
[java.lang.ClassNotFoundException: com.sun.xml.bind.v2.ContextFactory]] with root cause

java.lang.ClassNotFoundException: com.sun.xml.bind.v2.ContextFactory
        at org.springframework.boot.web.embedded.tomcat.TomcatEmbeddedWebappClassLoader.loadClass(TomcatEmbeddedWebappClassLoader.java:72) ~[spring-boot-2.3.1.RELEASE.jar!/:2.3.1.RELEASE]
        at org.apache.catalina.loader.WebappClassLoaderBase.loadClass(WebappClassLoaderBase.java:1188) ~[tomcat-embed-core-9.0.36.jar!/:9.0.36]
        at javax.xml.bind.ServiceLoaderUtil.nullSafeLoadClass(ServiceLoaderUtil.java:92) ~[jakarta.xml.bind-api-2.3.3.jar!/:2.3.3]
        at javax.xml.bind.ServiceLoaderUtil.safeLoadClass(ServiceLoaderUtil.java:125) ~[jakarta.xml.bind-api-2.3.3.jar!/:2.3.3]
        at javax.xml.bind.ContextFinder.newInstance(ContextFinder.java:230) ~[jakarta.xml.bind-api-2.3.3.jar!/:2.3.3]
        at javax.xml.bind.ContextFinder.find(ContextFinder.java:375) ~[jakarta.xml.bind-api-2.3.3.jar!/:2.3.3]
        at javax.xml.bind.JAXBContext.newInstance(JAXBContext.java:691) ~[jakarta.xml.bind-api-2.3.3.jar!/:2.3.3]
        at javax.xml.bind.JAXBContext.newInstance(JAXBContext.java:632) ~[jakarta.xml.bind-api-2.3.3.jar!/:2.3.3]
        at org.springframework.http.converter.xml.AbstractJaxb2HttpMessageConverter.lambda$getJaxbContext$0(AbstractJaxb2HttpMessageConverter.java:110) ~[spring-web-5.2.7.RELEASE.jar!/:5.2.7.RELEASE]
        at java.base/java.util.concurrent.ConcurrentHashMap.computeIfAbsent(ConcurrentHashMap.java:1705) ~[na:na]
        at org.springframework.http.converter.xml.AbstractJaxb2HttpMessageConverter.getJaxbContext(AbstractJaxb2HttpMessageConverter.java:108) ~[spring-web-5.2.7.RELEASE.jar!/:5.2.7.RELEASE]
        at org.springframework.http.converter.xml.AbstractJaxb2HttpMessageConverter.createMarshaller(AbstractJaxb2HttpMessageConverter.java:51) ~[spring-web-5.2.7.RELEASE.jar!/:5.2.7.RELEASE]
        at org.springframework.http.converter.xml.Jaxb2RootElementHttpMessageConverter.writeToResult(Jaxb2RootElementHttpMessageConverter.java:181) ~[spring-web-5.2.7.RELEASE.jar!/:5.2.7.RELEASE]
        at gov.nasa.pds.api.engineering.serializer.XmlProductSerializer.writeToResult(XmlProductSerializer.java:69) ~[classes!/:0.3.0]
        at org.springframework.http.converter.xml.AbstractXmlHttpMessageConverter.writeInternal(AbstractXmlHttpMessageConverter.java:85) ~[spring-web-5.2.7.RELEASE.jar!/:5.2.7.RELEASE]
        at org.springframework.http.converter.AbstractHttpMessageConverter.write(AbstractHttpMessageConverter.java:227) ~[spring-web-5.2.7.RELEASE.jar!/:5.2.7.RELEASE]
        at org.springframework.web.servlet.mvc.method.annotation.AbstractMessageConverterMethodProcessor.writeWithMessageConverters(AbstractMessageConverterMethodProcessor.java:290) ~[spring-webmvc-5.2.7.RELEASE.jar!/:5.2.7.RELEASE]
        at org.springframework.web.servlet.mvc.method.annotation.HttpEntityMethodProcessor.handleReturnValue(HttpEntityMethodProcessor.java:219) ~[spring-webmvc-5.2.7.RELEASE.jar!/:5.2.7.RELEASE]
        at org.springframework.web.method.support.HandlerMethodReturnValueHandlerComposite.handleReturnValue(HandlerMethodReturnValueHandlerComposite.java:82) ~[spring-web-5.2.7.RELEASE.jar!/:5.2.7.RELEASE]
```
##  🏞Screenshots
```
Whitelabel Error Page

This application has no explicit mapping for /error, so you are seeing this as a fallback.
Thu Jul 22 14:48:51 PDT 2021
There was an unexpected error (type=Internal Server Error, status=500).
```

## 🖥 System Info

---

** :unicorn: Applicable requirements**

**Comment by tloubrieu-jpl** [comment]
This is corrected in version 0.4.0-SNAPSHOT, see commit https://github.com/NASA-PDS/registry-api-service/commit/f347cd06be5826cf42e670c834464cedd6c477be

**Comment by jordanpadams** [comment]
@tloubrieu-jpl @tdddblog  is this related to the issue GEO is seeing? If so, can we tag a patch ASAP and notify them of the fix?

**Comment by tloubrieu-jpl** [comment]
@jordanpadams I notified Dan Scholes in the email thread and he is using 0.4.0-SNAPSHOT now and confirmed that works (email 07/23 at 12:17pm).

I would do a patch version for the other users.
